name: Proves de CI a GitHub

on:
  push:
    branches:
      - main

jobs:
  una_tasca_automatica:
    runs-on: ubuntu-latest
    steps:
      - name: Mostra un missatge per consola
        run: echo "La meva primera GitHub Action a DAW-M8"
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: main
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install Flask
        run: pip install Flask